name: Tagging main using pyproject.toml
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Tag main using pyproject.toml
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TLSSYSLOG_TAGGING_PAT }}
    - name: The new tag
      id: computed-tag
      run: |
        set -e
        TAG=$(cat pyproject.toml \
          | grep --extended-regexp "^version =" \
          | grep --extended-regexp --only-matching "[0-9]+\.[0-9]+.[0-9]+[-\.\+a-zA-Z0-9]*" \
          | head --lines=1)
        echo "tag=v$TAG" >> "$GITHUB_OUTPUT"
    - name: Tag main depending on the value in pyproject.toml
      uses: djordon/git-autotag-action@v0.7.0-beta2
      with:
        tag: ${{ steps.computed-tag.outputs.tag }}
